pipeline {
    agent any

    stages {
        stage('Construir imagen Docker') {
            steps {
                script {
                    withDockerRegistry([credentialsId: 'adrabencheeduit']) {
                      def dockerImage = docker.build('adrabencheeduit/test:latest', 'Jenkins_test')
                      dockerImage.push()
                    }
                }
            }
        }

        stage('Ejecutar contenedor') {
            steps {
                script {
                    def myContainer = docker.image('adrabencheeduit/test:latest').run('--name test-container --privileged --hostname test-container')
                }
            }
        }
    }
}


