pipeline {
    agent any

    stages {
      withDockerRegistry([credentialsId: 'adrabencheeduit', url: 'http://registry.domain.com:5000']) {
        stage('Construir imagen Docker') {
            steps {
                script {
                    def dockerImage = docker.build('test:latest', 'Jenkins_test')
                    dockerImage.push()
                }
            }
        }
      }

        stage('Ejecutar contenedor') {
            steps {
                script {
                    def myContainer = docker.image('adrabencheeduit/test:latest').run('--name test-container --privileged --hostname test-container-d')
                }
            }
        }
    }
}

